package com.example;

/* Not applicable when using Spring Boot
import java.io.IOException;
import java.util.Properties;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration; */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * A simple Hello World example using Hibernate ORM.
 * <p><b>Remark:</b> <code>@SpringBootApplication</code> automatically activates
 * component scanning, auto-configuration, and JPA repositories (if you need
 * <code>@EnableJpaRepositories</code>, Spring Boot does this automatically if
 * repositories are in the same package).<br>
 * <code>@SpringBootApplication</code> initiates component scanning and
 * auto-configuration. This annotation contains the following annotations:
 * <ul>
 * <li><code>@Configuration</code>: Tags the class as a source of bean
 * definitions</li>
 * <li><code>@EnableAutoConfiguration</code>: Tells Spring Boot to start adding
 * beans based on</li>
 * <li><code>@ComponentScan</code>: Tells Spring to look for other components,
 * configurations, and services<br>
 * Thus, Spring is looking for 
 * <ul>
 * <li><code>@Component</code> - Generic Spring bean</li>
 * <li><code>@Service</code> - Service bean (special case of Component)</li>
 * <li><code>@Repository</code> - Repository bean</li>
 * <li><code>@Controller</code> / <code>@RestController</code> - Web controller</li>
 * <li><code>@Configuration</code> - Configuration class</li>
 * <li><code>@Entity</code> - JPA entity (goes to Hibernate)
 * </Ul>
 * </li>
 * </ul>
 * <br>
 * So Spring Boot automatically finds the <code>MessageService</code> and
 * registers as a bean. <code>HelloWorldRunner</code> is also registered as a
 * bean. <code>Messagerepository</code> is dynamically generated by Spring Data JPA(!)
 * → A proxy class that implements all CRUD methods from <code>JpaRepository</code>.
 * 
 * @version 1.0 - Using hibernate.cfg.xml
 * @version 1.1 - Using application.properties
 * @author Thomas Schulz
 */
@SpringBootApplication
public class HelloWorld {
    /**
     * Main method to run the Hello World example.
     * @param args
     */
    public static void main(String[] args) {
        // Create SessionFactory from hibernate.cfg.xml
        /* Not applicable when using Spring Boot
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); */

        // Create SessionFactory from application.properties
        /* Not applicable when using Spring Boot
        Properties props = new Properties();
        try {
            props.load(ClassLoader.getSystemResourceAsStream("application.properties"));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        Configuration config = new Configuration();
        config.setProperties(props);
        config.addAnnotatedClass(Message.class);
        SessionFactory sessionFactory = config.buildSessionFactory();

        // Session öffnen
        Session session = sessionFactory.openSession();
        session.beginTransaction();

        // Neues Objekt speichern
        Message msg = new Message("Hello World with Hibernate and application.properties!");
        session.persist(msg);

        // Commit
        session.getTransaction().commit();

        // Objekt auslesen
        Message loaded = session.get(Message.class, msg.getId());
        System.out.println("Geladen: " + loaded.getText());

        session.close();
        sessionFactory.close(); */
        
        
        SpringApplication.run(HelloWorld.class, args);
    }
}
